### ISSUE TITLE
Empty paragraphs

### ISSUE THREAD

**Issue by iefserge** [micnews/html-to-article-json#11]
@kesla I noticed parser keeps paragraphs that contain line breaks only, do you think it makes sense to remove those?

```
{
  type: 'paragraph',
  children: [
    {
      type: 'linebreak'
    },
    {
      type: 'linebreak'
    }
  ]
}
```

**Comment by kesla** [comment]
@iefserge there are use cases where these are needed - this whole project originates in a WYSIWYG-editor - and then empty paragraphs like this is needed. Once more stable I'm going to revisit this idea, so if possible I'd like to build it now so that it'll work good then

Should we create an option for it perhaps?

**Comment by iefserge** [comment]
@kesla you're right, this module's job is to simply parse html as is. Modifications like this is completely different task.

**Comment by kesla** [comment]
@iefserge yeah, I think that the goal here should be to parse & normalize html to a representation that corresponds to the visual representation. So, for example, removing completely empty elements that aren't rendered I think is fine to remove in the normalization phase.
